### ISSUE TITLE
date format partially used

### ISSUE THREAD

**Issue by PierreDurrr** [InsertDisc/pattrmm#22]
Using `date_format: 2` (dd/mm) is partially working, as only first definition is using it.
Next definitions are back to default format (mm/dd):

```yaml
overlays:
# RETURNING 22/09/2023
  TV_Top_TextCenter_Returning_22/09/2023:
    template:
    - name: TV_Top_TextCenter
      weight: 35
      text: "NOUVEL ÉPISODE LE 22/09"
      color: "#FFFFFF"
      back_color: "#81007F"
    tmdb_discover:
      air_date.gte: 09/22/2023
      air_date.lte: 09/22/2023
      with_status: 0
      limit: 500
    filters:
      last_episode_aired.before: 08/07/2023

# RETURNING 09/23/2023
  TV_Top_TextCenter_Returning_09/23/2023:
    template:
    - name: TV_Top_TextCenter
      weight: 35
      text: "NOUVEL ÉPISODE LE 09/23"
      color: "#FFFFFF"
      back_color: "#81007F"
    tmdb_discover:
      air_date.gte: 09/23/2023
      air_date.lte: 09/23/2023
      with_status: 0
      limit: 500
    filters:
      last_episode_aired.before: 08/07/2023
```
